<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ArchiMate" nsURI="https://ict.hvl.no/people/patrick-stunkel/metamodels/archimate"
    nsPrefix="archimate">
  <eClassifiers xsi:type="ecore:EClass" name="Architecture">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ArchitectureElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="associations" upperBound="-1"
        eType="#//Association" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchitectureElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//ArchitectureElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="#//ArchitectureElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//ArchitectureElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="#//ArchitectureElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//ArchitectureElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataEntity" eSuperTypes="#//ArchitectureElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="#//ArchitectureElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Association">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ArchitectureElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ArchitectureElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
