<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SimpleBPMN" nsURI="https://ict.hvl.no/people/patrick-stunkel/metamodels/bpmn"
    nsPrefix="bpmn">
  <eClassifiers xsi:type="ecore:EClass" name="BPMNDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataObjects" upperBound="-1"
        eType="#//DataObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pools" upperBound="-1"
        eType="#//Pool" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//FlowNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flows" upperBound="-1"
        eType="#//SequenceFlow" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pool">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowNode" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//SequenceFlow" eOpposite="#//SequenceFlow/src"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//SequenceFlow" eOpposite="#//SequenceFlow/trg"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pool" eType="#//Pool"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActivityType">
    <eLiterals name="MANUAL"/>
    <eLiterals name="SERVICE" value="1"/>
    <eLiterals name="BUSINESS_RULE" value="2"/>
    <eLiterals name="MESSAGE_SEND" value="3"/>
    <eLiterals name="MESSAGE_RECV" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//FlowNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ActivityType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="consumes" upperBound="-1"
        eType="#//DataObject" eOpposite="#//DataObject/consumers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="produces" upperBound="-1"
        eType="#//DataObject" eOpposite="#//DataObject/producers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GatewayType">
    <eLiterals name="AND"/>
    <eLiterals name="XOR" value="1"/>
    <eLiterals name="EVENT_BASED" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gateway" eSuperTypes="#//FlowNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//GatewayType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EventType">
    <eLiterals name="START"/>
    <eLiterals name="END" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//FlowNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//EventType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceFlow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//FlowNode"
        eOpposite="#//FlowNode/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trg" lowerBound="1" eType="#//FlowNode"
        eOpposite="#//FlowNode/incoming"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="consumers" upperBound="-1"
        eType="#//Activity" eOpposite="#//Activity/consumes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="producers" upperBound="-1"
        eType="#//Activity" eOpposite="#//Activity/produces"/>
  </eClassifiers>
</ecore:EPackage>
